clock_model       : high_quality_tcxo
vel_process_psd   : 5.0
att_process_psd   : 0.01
sec_to_skip       : 0.0
intmd_freq        : 0.0
samp_freq         : 6.25e6
sim_dt            : 0.01
meas_dt           : 0.02
tap_epl_wide      : 0.5
tap_epl           : 0.5
tap_epl_narrow    : 0.5
init_cb           : 0.0
init_cd           : 5.9e-7
init_cov          : [9.0, 9.0, 9.0, 0.1, 0.1, 0.1, 0.01, 0.01, 0.01, 1.0, 0.05]
jammer_modulation : BPSK
jammer_type       : BLWN
j2s               : 23
cno               : 40
add_init_err      : false
is_multi_antenna  : true
n_ant             : 4
ant_xyz_0         : [0.0, 0.0, 0.0]
ant_xyz_1         : [0.09514, 0.0, 0.0]
ant_xyz_2         : [0.0, -0.09514, 0.0]
ant_xyz_3         : [0.09514, -0.09514, 0.0]
n_runs            : 12

# out_folder        : /media/daniel/Sturdivant/Thesis-Results/Correlator-Sim
out_folder : results/Correlator-Sim
# scenario          : ground-sim
# init_tow          : 507260.0
# week              : 2352
# data_file         : data/ground_sim.bin
# ephem_file        : data/gps_skydel_2025_02_07.bin
scenario          : drone-sim
init_tow          : 494993.0
week              : 2328
data_file         : data/drone_sim.bin
ephem_file        : data/gps_skydel_2024_08_23.bin

# J2S (dB) | C/No (dB-Hz)
# ---------|-------------
#     0    |     45.3   
#    13.7  |     44   
#    18.8  |     42      
#    22    |     40      
#    24.7  |     38      
#    27    |     36      
#    29.2  |     34      
#    31.3  |     32      
#    33.4  |     30      
#    35.5  |     28      
#    37.5  |     26      
#    39.5  |     24      
#    41.5  |     22      
#    43.5  |     20      
#    45.5  |     18      