# GENERAL
scenario: Run29
ms_to_skip: 70
ms_to_process: 115500
ms_chunk_size: 1000
ms_read_size: 20
# the file extension is assumed to be '*-i.bin' where 'i' is the antenna number (0-3)
in_file: ./data/SigSim
out_folder: /media/daniel/Sturdivant/Thesis-Data/Signal-Sim/drone-sim-2/CNo_40_dB
reference_pos_x: 0.0
reference_pos_y: 0.0
reference_pos_z: 0.0
log_level: warn

# RFSIGNAL
samp_freq: 6.25e6
intmd_freq: 0.0
is_complex: true
bit_depth: 16
signals: gps_l1ca
max_channels: 10
is_multi_antenna: true
n_ant: 4
ant_xyz_0: [0.0, 0.0, 0.0]
ant_xyz_1: [0.09514, 0.0, 0.0]
ant_xyz_2: [0.0, -0.09514, 0.0]
ant_xyz_3: [0.09514, -0.09514, 0.0]

# ACQUISITION
doppler_range: 5000.0
doppler_step: 250.0
num_coh_per: 1
num_noncoh_per: 5
threshold: 15.0
max_failed_attempts: 16

# TRACKING
min_converg_time_ms: 100
tap_epl_wide: 0.5
tap_epl: 0.3
tap_epl_narrow: 0.1
pll_bandwidth_wide: 6.0
fll_bandwidth_wide: 2.5
dll_bandwidth_wide: 1.0
pll_bandwidth: 3.0
fll_bandwidth: 0.1
dll_bandwidth: 0.1
pll_bandwidth_narrow: 1.0
fll_bandwidth_narrow: 0.001
dll_bandwidth_narrow: 0.001
cno_alpha: 0.02

# MEASUREMENTS
meas_freq: 5
process_std_vel: 10
process_std_att: 0.01
clock_model: high_quality_tcxo
nominal_transit_time: 0.069
use_psr: true
use_doppler: true
use_adr: false
use_cno: true
do_vt: true
